version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    env_file:
      .env
    ports:
      - "5435:5432" # проброс порта для доступа к PostgreSQL

  nats-streaming:
    image: nats-streaming:alpine
    ports:
      - "4222:4222"  # порт для подключения клиентов
      - "8222:8222"  # порт для административного доступа

  clickhouse:
    image: clickhouse/clickhouse-server:24.1-alpine
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: secret
    ports:
      - "8123:8123"  # порт HTTP интерфейса
      - "9000:9000"  # порт TCP интерфейса

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379" # проброс порта для доступа к Redis