version: "3.7"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: streamed_order_viewer_db
    hostname: postgres
    env_file:
      - .env
    ports:
      - "5435:5435" # проброс порта для доступа к PostgreSQL

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"  # порт для подключения клиентов
      - "8222:8222"  # порт для административного доступа

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # порт HTTP интерфейса
      - "9000:9000"  # порт TCP интерфейса
      - "9009:9009"  # порт для терминала ClickHouse
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml  # монтирование конфигурационного файла
      - ./clickhouse/data:/var/lib/clickhouse  # монтирование директории данных
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # проброс порта для доступа к Redis
    volumes:
      - ./redis/data:/data # монтирование директории данных Redis